{% set version = '1.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-filematrix
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/filematrix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/filematrix/filematrix_{{ version }}.tar.gz
  sha256: 0bf0c29bcab0d1bec7d80253899cc41581b2f0d2d236a7c1d25590f36c906aec

build:
  noarch: generic
  number: 1005
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('filematrix')"           # [not win]
    - "\"%R%\" -e \"library('filematrix')\""  # [win]

about:
  home: https://github.com/andreyshabalin/filematrix
  license: LGPL-3.0-only
  summary: Interface for working with large matrices stored in files, not in computer memory.
    Supports multiple non-character data types (double, integer, logical and raw) of
    various sizes (e.g. 8 and 4 byte real values). Access to parts of the matrix is
    done by indexing,  exactly as with usual R matrices. Supports very large matrices.
    Tested on multi-terabyte matrices. Allows for more than 2^32 rows or columns. Allows
    for quick addition of extra columns to a filematrix. Cross-platform as the package
    has R code only.
  license_family: LGPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
